// Virtual module: MDX page module map. Generated by the same discovery
// plugin pass, mapping each page slug → its content file path so the MDX
// renderer can `import` the compiled MDX module for a route. MDX files
// live OUTSIDE app/ (editors' tree), so the renderer resolves them through
// this map instead of guessing paths at runtime.
import type { Plugin } from "vite";
import { resolve } from "node:path";
import { discoverContent, type ContentManifest } from "./content-discovery";
import { buildConfig } from "./seo-config-loader";

const VIRTUAL_ID = "virtual:mdx-page-modules";
const VIRTUAL_RESOLVED = "\0" + VIRTUAL_ID;

export function mdxPageModulesPlugin(): Plugin {
  let code = "export const mdxPageModules = {};\n";
  let contentDirAbs = "";

  function refresh(): void {
    const manifest: ContentManifest = discoverContent(contentDirAbs);
    // EAGER static imports: prerender (ssr:false) runs route components in a
    // server render pass where effects never fire — the module must resolve
    // synchronously so MDX content lands IN the prerendered HTML (no client
    // fetch flash). All pages bundle into the client chunk (small site, fine).
    // Pages key by slug; author records key by `__author__<id>` so
    // the author renderer can resolve bios without colliding with slugs.
    const imports: string[] = [];
    const mapLines: string[] = [];
    for (const page of manifest.pages) {
      // Deferred pages must not ship their content in the eager client bundle.
      if (page.frontmatter.draft) continue;
      const importPath = resolve(contentDirAbs, page.file).replaceAll("\\", "/");
      const ident = `page_${page.slug.replaceAll("-", "_").replaceAll("/", "_")}`;
      imports.push(`import * as ${ident} from ${JSON.stringify(importPath)};`);
      mapLines.push(`  ${JSON.stringify(page.slug)}: ${ident},`);
    }
    const authorsEnabled = buildConfig(process.cwd()).news?.authorsEnabled !== false;
    for (const author of authorsEnabled ? manifest.authors.values() : []) {
      const importPath = resolve(contentDirAbs, author.file).replaceAll("\\", "/");
      const ident = `author_${author.authorId.replaceAll("-", "_")}`;
      imports.push(`import * as ${ident} from ${JSON.stringify(importPath)};`);
      mapLines.push(`  ${JSON.stringify(`__author__${author.authorId}`)}: ${ident},`);
    }
    code = `${imports.join("\n")}\nexport const mdxPageModules = {\n${mapLines.join("\n")}\n};\n`;
  }

  return {
    name: "mdx-page-modules",
    enforce: "pre",
    configResolved(config) {
      contentDirAbs = resolve(config.root, "content");
      refresh();
    },
    configureServer(server) {
      const invalidate = async (file: string): Promise<void> => {
        if (!file.includes("/content/") || !file.endsWith(".mdx")) return;
        try {
          refresh();
          const mod = server.moduleGraph.getModuleById(VIRTUAL_RESOLVED);
          if (mod) await server.moduleGraph.invalidateModule(mod);
        } catch {
          // discovery plugin reports the error; silence here is fine
        }
      };
      server.watcher.on("add", invalidate);
      server.watcher.on("unlink", invalidate);
      server.watcher.on("change", invalidate);
    },
    resolveId(id) {
      if (id === VIRTUAL_ID) return VIRTUAL_RESOLVED;
    },
    load(id) {
      if (id !== VIRTUAL_RESOLVED) return;
      return code;
    },
  };
}
